version: 2.1

dev_filter: &dev_filter
  filters:
    # branches:
    #   only:
    #     - master
    tags:
      only: 
        - dev.20

qa_filter: &qa_filter
  filters:
#     branches:
#         only:
#           - master
    tags:
      only:
        - qa.*
  
jobs:

  build-and-test:
    
    docker:
      - image: tomcat:latest
        auth:
            username: pavithra2818
            password: Pavi@2818
    steps:
      - checkout
      - run:
          name: Branch
          command: echo "${CIRCLE_BRANCH}"
          # Update this line with the directory that contains your tests project file
#           working_directory: ~/project/App.Tests
#           name: Run tests
#           command: |
#             dotnet test

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  sample: 
    jobs:
      - build-and-test:
          <<: *dev_filter
          name: checkout-code-dev
          context: DEV

  qa-plan-deploy:
    jobs: 
      - build-and-test:
          <<: *qa_filter
          name: checkout-code-qa
          context: DEV
              




export CIRCLECI_TOKEN="YOUR_API_TOKEN"
export PROJECT_SLUG="github/username/my-repo"
export TAG="$CIRCLE_TAG"

curl -X POST -H "Circle-Token: $CIRCLECI_TOKEN" \
     -H "Content-Type: application/json" \
     -d '{
       "branch": "main",
       "parameters": {
         "tag": "'"$TAG"'"
       }
     }' \
     "https://circleci.com/api/v2/project/$PROJECT_SLUG/pipeline"
